In [7]:
import numpy as np
from sklearn import preprocessing

In [8]:
feature = np.array([[-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])
feature

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [9]:
#Rescaling the feature
#Using MinMax scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [10]:
#Using Standard scaler(mean of 0 and sd of 1)
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(feature)
standardized

array([[-1.26687088],
       [-0.39316683],
       [-0.17474081],
       [ 0.0436852 ],
       [ 1.79109332]])

In [11]:
#Normalizing observations
features = np.array([[0.5, 0.5],
                     [1.1, 3.4],
                     [1.5, 20.2],
                     [1.63, 34.4],
                     [10.9, 3.3]])
normalizer = preprocessing.Normalizer()
normalizer.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [13]:
#Generating polynomial features for nonlinear relationships
features  = np.array([[2,4],
                      [2,3],
                      [4,5],
                      [1,5]])
poly = preprocessing.PolynomialFeatures(degree=3)
poly.fit_transform(features)


array([[  1.,   2.,   4.,   4.,   8.,  16.,   8.,  16.,  32.,  64.],
       [  1.,   2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  1.,   4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.],
       [  1.,   1.,   5.,   1.,   5.,  25.,   1.,   5.,  25., 125.]])