In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [3]:
#Encoding nominal features
features = np.array([['Texas'],
                     ['California'],
                     ['Texas'],
                     ['Delaware'],
                     ['Texas']])
one_hot = preprocessing.LabelBinarizer()
one_hot.fit_transform(features)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

In [5]:
pd.get_dummies(features[:,0])

California  Delaware  Texas
0       False     False   True
1        True     False  False
2       False     False   True
3       False      True  False
4       False     False   True

In [6]:
multiclass = [('Texas', 'Florida'),
              ('California', 'Alabama'),
              ('Texas', 'Florida'),
              ('Delaware', 'Florida'),
              ('Texas', 'Alabama')]
multi_hot = preprocessing.MultiLabelBinarizer()
multi_hot.fit_transform(multiclass)

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [7]:
multi_hot.classes_

array(['Alabama', 'California', 'Delaware', 'Florida', 'Texas'],
      dtype=object)

In [11]:
#Encoding ordinal categorical features
score = {'Score':['Low', 'Low', 'Medium', 'High', 'Medium', 'Low', 'High']}
df = pd.DataFrame(score)
#Create a mapper
scale_mapper = {'Low':1, 'Medium':2, 'High':3}
df['Score'].replace(scale_mapper)


/tmp/ipykernel_24115/579986660.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Score'].replace(scale_mapper)


0    1
1    1
2    2
3    3
4    2
5    1
6    3
Name: Score, dtype: int64

In [17]:
#Encoding dictonaries of features
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse=False)
data_dict =[{'Red':2, 'Blue':4},
            {'Red':1, 'Blue':2, 'Green':5},
            {'Blue':3, 'Green':4}]
features = vec.fit_transform(data_dict)
feature_names = vec.get_feature_names_out()
pd.DataFrame(features, columns=feature_names)

Blue  Green  Red
0   4.0    0.0  2.0
1   2.0    5.0  1.0
2   3.0    4.0  0.0

In [20]:
a = np.array([1, 2, 3])
a[2:]

array([3])